# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c87de35898fc377dbdec85a424caaa03"
application_url = "https://curriculum-strength-introduced-ratio.trycloudflare.com"
embedded = true
name = "enquery-app-webley"
handle = "enquery-app-webley"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://curriculum-strength-introduced-ratio.trycloudflare.com/auth/callback",
  "https://curriculum-strength-introduced-ratio.trycloudflare.com/auth/shopify/callback",
  "https://curriculum-strength-introduced-ratio.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
