# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b4fb5c0e0fa3c64554af1731c0563ab"
application_url = "https://ac-materials-bloomberg-liz.trycloudflare.com"
embedded = true
name = "enquiry-app"
handle = "enquiry-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://ac-materials-bloomberg-liz.trycloudflare.com/auth/callback",
  "https://ac-materials-bloomberg-liz.trycloudflare.com/auth/shopify/callback",
  "https://ac-materials-bloomberg-liz.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
